name: .MovieSystem.NET

on:
  push

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-dotnet-unit-tests:
    name: .NET Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dotnet dependencies
        run: dotnet restore
      - name: Build dotnet solution
        run: dotnet build --no-restore
      - name: Run dotnet unit tests
        run: dotnet test --no-build
  run-react-unit-tests:
    name: React Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: npm ci, build and test
      run: |
        npm ci
        npm run build --if-present
        npm test  
    defaults:
      run:
        working-directory: ./MoveShowcaseSPA/ClientApp/